version: '3.8'

services:

  app:
      container_name: php-8.0
      build:
          context: .
          dockerfile: Dockerfile
      image: template
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
          - ./:/var/www
      depends_on: 
          - redis
      networks: 
          - example-network

  # nginx
  nginx:
      container_name: nginx
      image: nginx:alpine
      restart: unless-stopped
      ports: 
          - "8989:80"
      volumes: 
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d/
      networks: 
          - example-network

  #PHP
  #php:
  #  image: php:7.4-fpm
  #  volumes:
  #    - ./:/var/www
  #  networks:
  #    - example-network

  # db mysql
  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - example-network

# redis
  redis:
    container_name: redis
    image: redis:latest
    networks: 
      - example-network

networks:
  example-network:
    driver: bridge
